### ISSUE TITLE
Feedback squadpage

### ISSUE THREAD

**Issue by Patrickkhr** [Jason2426/connect-your-tribe-squad-page#1]
Wat is mooi, wat werkt goed?

Clean en mooi design, goed gebruikt gemaakt van witruimte.
Animaties werken goed en het "klik voor muziek" element is erg leuk, heb ik nog nergens anders gezien.

Wat kan beter, wat werkt niet zo goed?

Het muziek element kan niet op pauze, sommige afbeeldingen worden uitgerekt misschien ligt het aan de image of misschien kan je het oplossen door de image als background te gebruiken.

**Comment by Jason2426** [comment]
Thx voor de tops 😄 

De tips zal ik gebruiken voor de volgende keren, met name de tip voor afbeeldingen. Ik zal proberen om deze dynamisch te maken en geen vaste waardes mee te geven de volgende keren. width100% gebruiken en de heightAuto
