### ISSUE TITLE
Feedback squad page

### ISSUE THREAD

**Issue by lisavanmansom** [Jason2426/connect-your-tribe-squad-page#2]
Wat is mooi, wat werkt goed? 
Leuk design,  het is goed overzichtelijk en door het witgebruik ziet het er clean uit.

Wat kan beter? Wat werkt niet zo goed?
Het kleurgebruik grijs op zwart slaagt niet op contrast.

<img width="400" alt="Scherm­afbeelding 2024-02-16 om 11 22 21" src="https://github.com/Jason2426/connect-your-tribe-squad-page/assets/144007419/7af45508-92a5-4df5-ba3f-f645bee3993a">

Ik zou bij de foto's object-fit: contain; of object-fit: cover; gebruiken want nu worden de foto's uit proporties gehaald

**Comment by Jason2426** [comment]
Thx voor de tops 😄 

Klopt dit had ik zelf al door maar heb ervoor gekozen bij dit project om het te maken hoe ik zelf wilde en niet persee gebruikers-gericht. Zal er bij projecten van opdrachtgevers wel altijd op letten. Goede tip voor de images ik zal de volgende keren geen vaste waardes proberen mee te geven maar de image width laten bepalen door de breedte en hoogte van de container of article waar die in staat.
