### ISSUE TITLE
Ontwerp analyseren

### ISSUE THREAD

**Issue by Abeeryu** [Jason2426/connect-your-tribe-squad-page#3]
Wat is mooi, Wat werkt goed?

Ik vind het een leuke design met mooie animatie.

Wat kan beter, Wat werkt niet goed?

Misschien kan je een kleiner lettergroote gebruiken voor de titles. Ook kan je bijvoorbeeld voor de home button hetzelfde kleur groen als de members en scroll down gebruiken.

**Comment by Jason2426** [comment]
Thx voor de tops 😄, ben er zelf ook redelijk trots op. 

Qua tips, de lettergrootte voor de titels heb ik express zo groot gemaakt zodat het lekker leesbaar is voor iedereen en zodat ik een scroll for more tekst met animatie kon toevoegen maar ik had het inderdaad wat kleiner kunnen maken.
