### ISSUE TITLE
Feedback ontwerp

### ISSUE THREAD

**Issue by Jesse-Kramer** [Jason2426/connect-your-tribe-squad-page#4]
Wauw! Wat vet. Mooie site met al die "Zara" qoutes. Wordt ik heel enthousiast van.

Let even op het contrast van je Home knop.

**Comment by Jason2426** [comment]
Leuke issue maar heb ik eigenlijk niks aan, GRAPJE. Thx voor de complimenten. 

Zal de volgende keren beter letten op de kleurcontrasten die ik gebruik.
